#! /bin/bash
wall $`hostnamectl | grep 'Architecture\|Kernel\|Operating System'`
printf "Number of Physical CPUs: "
nproc
printf "Number of Virtual CPUs: "
cat /proc/cpuinfo | grep processor | wc -l
free --mega | awk 'NR==2{printf "Current memory available: %sMB \nRAM Utilization rate:(%.2f%%)\n", $7,$3*100/$2 }'
df -h /
top -bn1 | grep load | awk '{printf "CPU Load: %.2f\n", $NF}'
printf "Last reboot: "
last reboot | head -n 1 | awk '{print $5, $6, $7}'
printf "LVM active: "
lsblk | grep lvm | awk '{if ($1) {print "yes";exit;} else {print "no"} }'
ss -t | wc -l
netstat -an | grep ESTABLISHED |  wc -l
w -h | wc -l
printf "IP adress: "
hostname -I | awk '{print $1}'
printf "MAC adress: "
ip link show | grep link/ether | awk '{print $2}'
printf "sudo.log count: "
grep USER=root /var/log/auth.log | wc -l
printf "journalctl count: "
journalctl _COMM=sudo | grep COMMAND | wc -l

